### ISSUE TITLE
从 notion 同步时老是出现时间错误

### ISSUE THREAD

**Issue by lanlin** [nonacosa/notion-site#2]
你好，在使用 notion-site 的过程中，老是在 github action 中看到如下的报错

```shell
✔ Generating blog post: Completed
panic: parsing time "2023-06-08T07:04:17.[57](https://github.com/Uranuslab/deputy-blog/actions/runs/5208364636/jobs/9396873279#step:5:58)Z0": extra text: "0"

goroutine 1 [running]:
github.com/pkwenda/notion-site/pkg.(*NotionAPI).mustParseDateTime(...)
	/usr/src/app/pkg/notion_api.go:194
github.com/pkwenda/notion-site/pkg.(*NotionAPI).changeStatus(_, _, {{0xc00034be90, 0x24}, {0x0, 0xedc0677c4, 0x0}, 0xc0000a3f30, {0x0, 0xedc137424, ...}, ...}, ...)
	/usr/src/app/pkg/notion_api.go:172 +0x41e
github.com/pkwenda/notion-site/pkg.processDatabase(0xc00038fc18, {0xc00002cea0?, 0x9c9a44?})
	/usr/src/app/pkg/generator.go:125 +0x5b2
github.com/pkwenda/notion-site/pkg.Run(0xc00038fc18)
	/usr/src/app/pkg/generator.go:31 +0xaf
github.com/pkwenda/notion-site/cmd.glob..func2(0xdc55[60](https://github.com/Uranuslab/deputy-blog/actions/runs/5208364636/jobs/9396873279#step:5:61)?, {0x9bf904?, 0x0?, 0x0?})
	/usr/src/app/cmd/root.go:32 +0x245
github.com/spf13/cobra.(*Command).execute(0xdc5560, {0xc000024240, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x6[63](https://github.com/Uranuslab/deputy-blog/actions/runs/5208364636/jobs/9396873279#step:5:64)
github.com/spf13/cobra.(*Command).ExecuteC(0xdc5560)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/pkwenda/notion-site/cmd.Execute()
	/usr/src/app/cmd/root.go:41 +0x25
main.main()
	/usr/src/app/main.go:6 +0x17
```

**Comment by lanlin** [comment]
fixed #3
